### ISSUE TITLE
Format percent downloaded when updating firmware

### ISSUE THREAD

**Issue by devilbiter** [prusa3d/Prusa-Firmware-SL1#13]
When updating the firmware, the "percent downloaded" isn't formatted and has about 16 digits. 
![IMG_20200305_093423128](https://user-images.githubusercontent.com/14806485/75991967-48baee80-5ec5-11ea-99d9-30dbd9c06ae2.jpg)

**Comment by fookatchu** [comment]
When it reaches 80% we have zero digits :). As a side note: My Autoupdate to 1.3.3 was only triggered when booting the machine, not when searching for a new firmware through the menu.

**Comment by filipkotoucek** [comment]
The issue with decimal points is fixed and will be included in release 1.4.0.

About the update. Since we switched the update mechanism to automatic updates, the "firmware update page" is used in 1.3.3 only for updates from USB. We added the button to force update check on "firmware update page" sou you can check manually during runtime.

All this (and more) will come in 1.4.0 :)

**Comment by filipkotoucek** [comment]
I just wanted to let you know this issue is fixed in out recent rc build https://github.com/prusa3d/Prusa-Firmware-SL1/releases/tag/1.4.0-rc.1. We plan to release the stable build in week or two.
