### ISSUE TITLE
Power Panic not working in Version 1.4

### ISSUE THREAD

**Issue by JKinch03** [prusa3d/Prusa-Firmware-SL1#24]
So about a week ago I was printing a model and I accidentally turned off a surge protector/power strip that the SL1 was plugged into. This immediately cut off all the power to the SL1, and when I turned the power strip back on (5 seconds later) the SL1 started up as it normally would, and I had to start the print over again. The shop says that the printer has power panic enabled, but nobody that I've talked to had heard about that.

**Comment by JakubSilar3D** [comment]
Hi, this is a known issue in 1.4. As the printing interruption during makes a visible mark, we are still reconsidering it, as implementation would cause user disappointment. So yes, the basic HW ability is there, the SW essentials are there, but the future is unclear, because with resin printers, there is a fundamental problem in restarting the print.
Feel free to reopen the issue, if you need more info or if you want to look at the problem from the perspective of community software development.
