### ISSUE TITLE
Unable to Connect to Unencrypted Network 

### ISSUE THREAD

**Issue by bghost36** [prusa3d/Prusa-Firmware-SL1#27]
Our network is setup in such a way that we register devices by MAC and then they are allowed to connect to a series of wireless networks. So, the issue is twofold.

One - I am unable to locate the MAC for the wireless card, the only MAC listed in the information I assume is for the ethernet port. Is this shared with the wireless or does the wireless have its own MAC and if so how can it be accessed? There is nothing in the printer menus or the handbook that mention where this info might be.

Two - I am unable to connect to a network that does not require a password to join and I am also unable to connect to a network that requires authentication to join. The only option for connecting is a password and it must be 8 characters long. This makes me unable to bypass connecting to the unencrypted network. Since a password is the only option I also cannot connect to the secure network because it requires a username from our side for authentication purposes.

The configuration of the networking for wifi makes it very difficult to use in a corporate environment. Any help or changes that come from this is much appreciated!

**Comment by filipkotoucek** [comment]
Hello @bghost36,
1. The MAC address of the WiFi is accessible (if you are connected to some network) in settings->network->wifi->(name of the network you are currently connected to).
2. Unfortunately you are correct and we do not support open WiFi networks. We are currently at the end of the release cycle and 1.5.0 is being beta tested now. So we can add this feature in the next feature release. But there is also good news. We are evaluating the complexity and planning to implement other security options such as WPA2 enterprise, so we will add this request for an open network in our consideration. BTW if you would like to, we will be happy to see any contributions to our code since there will be none to this point.
